mod accordion;
mod alert_dialog;
mod autocomplete;
mod avatar;
mod button;
mod checkbox;
mod checkbox_group;
mod collapsible;
mod combobox;
mod context_menu;
mod dialog;
mod drawer;
mod field;
mod fieldset;
mod form;
mod input;
mod menu;
mod menubar;
mod meter;
mod navigation_menu;
mod number_field;
mod otp_field;
mod popover;
mod preview_card;
mod progress;
mod radio_group;
mod scroll_area;
mod select;
mod separator;
mod slider;
mod switch;
mod tabs;
mod toast;
mod toggle;
mod toggle_group;
mod toolbar;
mod tooltip;

use gpui::{AnyElement, IntoElement};

pub struct DemoEntry {
    pub slug: &'static str,
    pub title: &'static str,
    /// Demos return their concrete element type; the registry erases it here
    /// so every entry fits one table (a fn pointer must name a single return
    /// type, and `AnyElement` is gpui's type-erased element).
    pub render: fn() -> AnyElement,
}

// Slugs are hyphenated to match the docs page URLs generated by
// scripts/build-site.mjs (`alert_dialog.md` -> `/components/alert-dialog.html`).
pub fn all() -> &'static [DemoEntry] {
    &[
        DemoEntry {
            slug: "accordion",
            title: "Accordion",
            render: || accordion::render().into_any_element(),
        },
        DemoEntry {
            slug: "alert-dialog",
            title: "Alert Dialog",
            render: || alert_dialog::render().into_any_element(),
        },
        DemoEntry {
            slug: "autocomplete",
            title: "Autocomplete",
            render: || autocomplete::render().into_any_element(),
        },
        DemoEntry {
            slug: "avatar",
            title: "Avatar",
            render: || avatar::render().into_any_element(),
        },
        DemoEntry {
            slug: "button",
            title: "Button",
            render: || button::render().into_any_element(),
        },
        DemoEntry {
            slug: "checkbox",
            title: "Checkbox",
            render: || checkbox::render().into_any_element(),
        },
        DemoEntry {
            slug: "checkbox-group",
            title: "Checkbox Group",
            render: || checkbox_group::render().into_any_element(),
        },
        DemoEntry {
            slug: "collapsible",
            title: "Collapsible",
            render: || collapsible::render().into_any_element(),
        },
        DemoEntry {
            slug: "combobox",
            title: "Combobox",
            render: || combobox::render().into_any_element(),
        },
        DemoEntry {
            slug: "context-menu",
            title: "Context Menu",
            render: || context_menu::render().into_any_element(),
        },
        DemoEntry {
            slug: "dialog",
            title: "Dialog",
            render: || dialog::render().into_any_element(),
        },
        DemoEntry {
            slug: "drawer",
            title: "Drawer",
            render: || drawer::render().into_any_element(),
        },
        DemoEntry {
            slug: "field",
            title: "Field",
            render: || field::render().into_any_element(),
        },
        DemoEntry {
            slug: "fieldset",
            title: "Fieldset",
            render: || fieldset::render().into_any_element(),
        },
        DemoEntry {
            slug: "form",
            title: "Form",
            render: || form::render().into_any_element(),
        },
        DemoEntry {
            slug: "input",
            title: "Input",
            render: || input::render().into_any_element(),
        },
        DemoEntry {
            slug: "menu",
            title: "Menu",
            render: || menu::render().into_any_element(),
        },
        DemoEntry {
            slug: "menubar",
            title: "Menubar",
            render: || menubar::render().into_any_element(),
        },
        DemoEntry {
            slug: "meter",
            title: "Meter",
            render: || meter::render().into_any_element(),
        },
        DemoEntry {
            slug: "navigation-menu",
            title: "Navigation Menu",
            render: || navigation_menu::render().into_any_element(),
        },
        DemoEntry {
            slug: "number-field",
            title: "Number Field",
            render: || number_field::render().into_any_element(),
        },
        DemoEntry {
            slug: "otp-field",
            title: "OTP Field",
            render: || otp_field::render().into_any_element(),
        },
        DemoEntry {
            slug: "popover",
            title: "Popover",
            render: || popover::render().into_any_element(),
        },
        DemoEntry {
            slug: "preview-card",
            title: "Preview Card",
            render: || preview_card::render().into_any_element(),
        },
        DemoEntry {
            slug: "progress",
            title: "Progress",
            render: || progress::render().into_any_element(),
        },
        DemoEntry {
            slug: "radio-group",
            title: "Radio Group",
            render: || radio_group::render().into_any_element(),
        },
        DemoEntry {
            slug: "scroll-area",
            title: "Scroll Area",
            render: || scroll_area::render().into_any_element(),
        },
        DemoEntry {
            slug: "select",
            title: "Select",
            render: || select::render().into_any_element(),
        },
        DemoEntry {
            slug: "separator",
            title: "Separator",
            render: || separator::render().into_any_element(),
        },
        DemoEntry {
            slug: "slider",
            title: "Slider",
            render: || slider::render().into_any_element(),
        },
        DemoEntry {
            slug: "switch",
            title: "Switch",
            render: || switch::render().into_any_element(),
        },
        DemoEntry {
            slug: "tabs",
            title: "Tabs",
            render: || tabs::render().into_any_element(),
        },
        DemoEntry {
            slug: "toast",
            title: "Toast",
            render: || toast::render().into_any_element(),
        },
        DemoEntry {
            slug: "toggle",
            title: "Toggle",
            render: || toggle::render().into_any_element(),
        },
        DemoEntry {
            slug: "toggle-group",
            title: "Toggle Group",
            render: || toggle_group::render().into_any_element(),
        },
        DemoEntry {
            slug: "toolbar",
            title: "Toolbar",
            render: || toolbar::render().into_any_element(),
        },
        DemoEntry {
            slug: "tooltip",
            title: "Tooltip",
            render: || tooltip::render().into_any_element(),
        },
    ]
}

pub fn find(slug: &str) -> Option<&'static DemoEntry> {
    all().iter().find(|entry| entry.slug == slug)
}
